ALTER TABLE repuestos ADD COLUMN IF NOT EXISTS ubicacion VARCHAR(160);
ALTER TABLE repuestos ADD COLUMN IF NOT EXISTS foto_nombre VARCHAR(180);
ALTER TABLE stock_bodega ADD COLUMN IF NOT EXISTS ubicacion VARCHAR(160);
